"""tasks/04 acceptance report for the GRPO arms: reads runs/grpo/*, the base eval, and the queue
logs on the store, and writes one Markdown file. Read-only over run dirs; no arm-vs-arm claims.

    uv run python scripts/grpo_report.py --out reports/tasks04_grpo_acceptance.md
"""

from __future__ import annotations

import argparse
import glob
import json
import re
import statistics as st
from pathlib import Path

RUNS = [
    "grpo_mixed_s1",
    "grpo_curated_s1",
    "grpo_easy_s1",
    "grpo_random_reward_s1",
    "grpo_format_only_s1",
    "grpo_mixed_s2",
    "grpo_curated_s2",
    "grpo_easy_s2",
    "grpo_mixed_s3",
    "grpo_curated_s3",
    "grpo_easy_s3",
]
ARMS = {
    "mixed": [1, 2, 3],
    "curated": [1, 2, 3],
    "easy": [1, 2, 3],
    "random_reward": [1],
    "format_only": [1],
}
BASE = Path("runs/eval/Qwen__Qwen3-4B-Base")
BASE_TRANSFER = Path(
    "results/phase1/transfer_pick/Qwen__Qwen3-4B-Base"
)  # gsm8k_500 base eval lives here
FINAL_UNITS = [
    ("test_300", "greedy"),
    ("test_300", "mean_at_k"),
    ("test_300", "pass_at_k"),
    ("ood_hard_200", "greedy"),
    ("ood_hard_200", "mean_at_k"),
    ("gsm8k_500", "greedy"),
    ("gsm8k_500", "mean_at_k"),
    ("val_mixed_100", "greedy"),
    ("val_mixed_100", "mean_at_k"),
]
RATE = 4.29


def load(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def rows(run_dir: Path):
    out = []
    for line in (run_dir / "train_log.jsonl").read_text().splitlines():
        if line.strip():
            r = json.loads(line)
            if not r.get("summary"):
                out.append(r)
    return out


def pct(x):
    return "—" if x is None else f"{100 * x:.1f}%"


def fmt(m):
    if m is None:
        return "pending"
    return f"{m['accuracy']:.3f} [{m['ci_low']:.3f},{m['ci_high']:.3f}] n={m['n_problems']} trunc {pct(m['truncation_rate'])}"


def queue_walls(store_logs: Path):
    """{job_name: [(wall_h, exit_code), ...]} from every grpo_queue_*.log on the store."""
    walls: dict[str, list[tuple[float, int]]] = {}
    for log in sorted(store_logs.glob("grpo_queue_*.log")):
        for m in re.finditer(
            r"\[queue\] (\S+) exit=(\d+) wall=([\d.]+) h", log.read_text(errors="replace")
        ):
            walls.setdefault(m.group(1), []).append((float(m.group(3)), int(m.group(2))))
    return walls


def eval_hours_from_mtimes(rd: Path):
    """Eval wall-clock from file mtimes when the queue's exit line is missing (a SIGTERM'd
    run_queue.py does not flush its buffered stdout): first val unit's config (written ~1–2 min
    after the job starts) to the final summary."""
    first = rd / "eval_checkpoints" / "step_100" / "val_mixed_100" / "greedy" / "config.yaml"
    last = rd / "eval" / "final" / "summary.json"
    if not (first.exists() and last.exists()):
        return None
    return round((last.stat().st_mtime - first.stat().st_mtime) / 3600 + 2 / 60, 2)


def mean_std(xs):
    xs = [x for x in xs if x is not None]
    if not xs:
        return "—"
    if len(xs) == 1:
        return f"{xs[0]:.3f}"
    return f"{st.mean(xs):.3f} ± {st.stdev(xs):.3f}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="reports/tasks04_grpo_acceptance.md")
    ap.add_argument("--store-logs", default="/lambda/nfs/rl-or-data/rlordata-artifacts/logs")
    a = ap.parse_args()
    walls = queue_walls(Path(a.store_logs))
    lines: list[str] = []
    w = lines.append
    w("# tasks/04 GRPO arms — acceptance report\n")
    w(
        "Generated by `scripts/grpo_report.py` from `runs/grpo/*` (restored from the store) and the queue logs. "
        "Per CLAUDE.md every number carries n, seed, bootstrap 95 % CI, truncation rate and config hash; "
        "per tasks/04 §Acceptance this report makes **no arm-vs-arm claims** (tasks/05).\n"
    )

    # ---- resolved config ----
    ref = Path("runs/grpo/grpo_mixed_s1")
    meta = load(ref / "meta.json") or {}
    gc = load(ref / "grpo_config.json") or {}
    w(
        "## 1. Resolved configuration (identical across the 11 runs except data_condition / reward / seed)\n"
    )
    keys = [
        "max_steps",
        "num_generations",
        "generation_batch_size",
        "per_device_train_batch_size",
        "gradient_accumulation_steps",
        "learning_rate",
        "lr_scheduler_type",
        "warmup_steps",
        "beta",
        "epsilon",
        "loss_type",
        "scale_rewards",
        "num_iterations",
        "max_completion_length",
        "temperature",
        "top_p",
        "vllm_mode",
        "vllm_gpu_memory_utilization",
        "vllm_max_model_length",
        "importance_sampling_level",
        "mask_truncated_completions",
        "vllm_importance_sampling_correction",
        "gradient_checkpointing",
        "bf16",
        "seed",
    ]
    w("| key | value |\n|---|---|")
    for k in keys:
        if k in gc:
            w(f"| {k} | {gc[k]} |")
    vers = meta.get("versions") or meta.get("packages") or {}
    if vers:
        w(
            f"| package versions | {', '.join(f'{k} {v}' for k, v in vers.items() if k in ('trl', 'vllm', 'peft', 'torch', 'transformers'))} |"
        )
    w(f"| GPU | {meta.get('gpu', 'NVIDIA H100 PCIe')} |")
    w("| policy sync | native vLLM LoRA (train/vllm_lora.py); never a bf16 merge |")
    w("| allocator | PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True (dc959d3) |")
    w("| vLLM engine process | spawn (9cb3e3a) |\n")

    # ---- per-run table ----
    w("## 2. Runs: provenance, wall-clock, cost\n")
    w(
        "| run | config hash | git SHA (train) | train GPU-h | train $ | eval GPU-h | eval $ | records | adapters |\n|---|---|---|---|---|---|---|---|---|"
    )
    tot_train = tot_eval = 0.0
    for name in RUNS:
        rd = Path("runs/grpo") / name
        b = load(rd / "budgets.json") or {}
        m = load(rd / "meta.json") or {}
        th = float(b.get("gpu_hours_train", 0))
        ev = [wh for wh, code in walls.get(f"eval_{name}", []) if code == 0]
        eh = ev[-1] if ev else eval_hours_from_mtimes(rd)
        eh_note = "" if ev or eh is None else "≈"
        n_rec = (
            sum(1 for _ in open(rd / "reward_records.jsonl"))
            if (rd / "reward_records.jsonl").exists()
            else 0
        )
        adapters = (
            sorted(p.name for p in (rd / "adapter").iterdir()) if (rd / "adapter").exists() else []
        )
        tot_train += th
        tot_eval += eh or 0
        w(
            f"| {name} | {(rd / 'config_hash.txt').read_text().strip()[:12]} | {str(m.get('git_sha', ''))[:7]} | {th:.2f} | {th * RATE:.0f} | "
            f"{'pending' if eh is None else f'{eh_note}{eh:.2f}'} | {'' if eh is None else f'{eh * RATE:.0f}'} | {n_rec:,} | {','.join(a.replace('step_', '') for a in adapters)} |"
        )
    failed = {k: [(wh, c) for wh, c in v if c != 0] for k, v in walls.items()}
    failed = {k: v for k, v in failed.items() if v}
    w(
        f"\nTotals: train {tot_train:.2f} GPU-h ≈ ${tot_train * RATE:.0f}; evals {tot_eval:.2f} GPU-h ≈ ${tot_eval * RATE:.0f}; "
        f"killed/failed attempts (not in the totals): "
        + ", ".join(f"{k} {sum(wh for wh, _ in v):.2f} h" for k, v in failed.items())
        + ".\n"
    )

    # ---- training stats ----
    w("## 3. Training reward and frac_reward_zero_std at steps 1 / 100 / 200 / 299\n")
    w(
        "Step 299 is the last step with a logged batch (step 300's row is the summary). Also: run max of "
        "sampling_logp_absdiff_mean (gate < 0.05 nats), mean completion length over the last 50 steps, and the "
        "share of completions at the 4,352 cap over steps 151–300.\n"
    )
    w(
        "| run | reward@1 / zero_std | @100 | @200 | @299 | last-50 reward / zero_std | max logp gap | len last-50 | cap hits 151–300 |\n|---|---|---|---|---|---|---|---|---|"
    )
    for name in RUNS:
        rd = Path("runs/grpo") / name
        rs = rows(rd)
        by = {r["step"]: r for r in rs}
        cells = []
        for s in (1, 100, 200, 299):
            r = by.get(s)
            cells.append(
                "—" if r is None else f"{r['reward_mean']:.3f} / {r['frac_reward_zero_std']:.3f}"
            )
        last = rs[-50:]
        w(
            f"| {name} | "
            + " | ".join(cells)
            + f" | {st.mean(r['reward_mean'] for r in last):.3f} / {st.mean(r['frac_reward_zero_std'] for r in last):.3f}"
            f" | {max(r['sampling_logp_absdiff_mean'] for r in rs):.4f} | {st.mean(r['completions_mean_length'] for r in last):.0f}"
            f" | {pct(st.mean(r['completions_clipped_ratio'] for r in rs if r['step'] > 150))} |"
        )
    w("")

    # ---- val curves ----
    w(
        "## 4. Val curve per run and per arm (val_mixed_100 greedy, n=100, adapter at steps 100 / 200 / 300)\n"
    )
    bv = load(BASE / "val_mixed_100" / "greedy" / "metrics.json")
    w(f"Base: {fmt(bv)}.\n")
    w("| run | step 100 | step 200 | step 300 |\n|---|---|---|---|")
    arm_vals: dict[str, dict[str, list[float]]] = {}
    for name in RUNS:
        rd = Path("runs/grpo") / name
        curve = (load(rd / "curves.json") or {}).get("val_greedy") or {}
        cells = []
        arm = name.replace("grpo_", "").rsplit("_s", 1)[0]
        for s in ("100", "200", "300"):
            c = curve.get(s)
            if c:
                cells.append(
                    f"{c['accuracy']:.3f} [{c['ci'][0]:.3f},{c['ci'][1]:.3f}] trunc {pct(c['truncation_rate'])}"
                )
                arm_vals.setdefault(arm, {}).setdefault(s, []).append(c["accuracy"])
            else:
                cells.append("pending")
        w(f"| {name} | " + " | ".join(cells) + " |")
    w("\n| arm (mean ± std across seeds) | step 100 | step 200 | step 300 |\n|---|---|---|---|")
    for arm in ARMS:
        d = arm_vals.get(arm, {})
        w(
            f"| {arm} (n_seeds={len(d.get('300', []))}) | "
            + " | ".join(mean_std(d.get(s, [])) for s in ("100", "200", "300"))
            + " |"
        )
    w("")

    # ---- final evals ----
    w("## 5. Final (step 300) evaluation per run\n")
    w(
        "Bootstrap 95 % CI; trunc = share of completions at the cap (flag > 5 % on test/val; reported on ood). "
        "pass@k on the test first-100 subset with 64 samples per problem.\n"
    )
    for split, dec in FINAL_UNITS:
        w(f"### {split} / {dec}\n")
        bm = load(BASE / split / dec / "metrics.json") or load(
            BASE_TRANSFER / split / dec / "metrics.json"
        )
        w(
            f"- base: {fmt(bm)}"
            + (
                f"; pass@1/8/64 {bm['pass_at_k']['1']:.3f}/{bm['pass_at_k']['8']:.3f}/{bm['pass_at_k']['64']:.3f}"
                if bm and dec == "pass_at_k"
                else ""
            )
        )
        per_arm: dict[str, list[float]] = {}
        for name in RUNS:
            rd = Path("runs/grpo") / name
            m = load(rd / "eval" / "final" / split / dec / "metrics.json")
            arm = name.replace("grpo_", "").rsplit("_s", 1)[0]
            extra = ""
            if m and dec == "pass_at_k":
                extra = f"; pass@1/8/64 {m['pass_at_k']['1']:.3f}/{m['pass_at_k']['8']:.3f}/{m['pass_at_k']['64']:.3f}"
            w(f"- {name}: {fmt(m)}{extra}")
            if m:
                per_arm.setdefault(arm, []).append(m["accuracy"])
        w(
            "- per arm, mean ± std across seeds: "
            + "; ".join(f"{arm} {mean_std(v)} (n_seeds={len(v)})" for arm, v in per_arm.items())
        )
        w("")

    # ---- sanity ----
    w("## 6. Sanity gates (tasks/04 §6)\n")
    w(
        "| run | reward records | protocol_vs_base ok / final units | eval_checkpoints stashed | C1 mean reward |\n|---|---|---|---|---|"
    )
    for name in RUNS:
        rd = Path("runs/grpo") / name
        n_rec = (
            sum(1 for _ in open(rd / "reward_records.jsonl"))
            if (rd / "reward_records.jsonl").exists()
            else 0
        )
        san = [
            load(Path(p)) for p in glob.glob(str(rd / "eval" / "final" / "*" / "*" / "sanity.json"))
        ]
        ok = sum(1 for s in san if s and s.get("protocol_vs_base") == "ok")
        stash = (
            sorted(p.name for p in (rd / "eval_checkpoints").iterdir())
            if (rd / "eval_checkpoints").exists()
            else []
        )
        c1 = ""
        if "random_reward" in name and (rd / "reward_records.jsonl").exists():
            recs = [json.loads(line) for line in open(rd / "reward_records.jsonl")]
            c1 = f"{st.mean(float(r.get('reward', 0)) for r in recs):.4f}"
        w(
            f"| {name} | {n_rec:,} | {ok} / {len(san)} | {','.join(s.replace('step_', '') for s in stash) or 'pending'} | {c1} |"
        )
    w("")
    w("## 7. Decisions this task file did not specify\n")
    for d in [
        "vLLM's EngineCore is spawned, not forked, on the eval path (`sampling/vllm_sampler.py`, 9cb3e3a): the fork inherited a warm libgomp pool and deadlocked in `init_device` — the cause of the box-1 and box-3 eval hangs. Training was never affected (the trainer initialises CUDA first, after which vLLM spawns anyway).",
        "The eval stage stashes each checkpoint's val eval under `eval_checkpoints/step_{n}/` and forces a re-sample of the shared `eval/val/` when it holds another adapter's result (`train/grpo_trl.py`, f08fdb5); without this, step 200 was skipped as 'already evaluated' and `curves.json` stayed empty.",
        "`PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` is set at the top of `train_grpo` (dc959d3) after curated_s1 OOMed in the step-5 backward with 15.9 GiB reserved-but-unallocated; micro-batch stays 4 × 16 for all 11 runs. Allocator-level only.",
        "`artifacts._sync_local` skips files whose size and mtime already match on the store (f4eec05); the unconditional copy of ~24 GB run dirs between eval jobs was approaching the 30-minute idle guard. The queue was stopped between jobs and relaunched once (06:49 UTC 2026-09-19) to pick this up; no job was running and the store already held the run dir.",
        "Run-dir `NOTES.md` files are gitignored (`runs/`); each run's notes are filled and live on the store next to the run, with the same content summarised in `notebook/LAB_NOTEBOOK.md`.",
        "Eval GPU-hours in §2 are the queue's wall-clock for the successful attempt; the two killed attempts of eval_grpo_mixed_s1 (0.30 h) and the failed first attempt of train_grpo_curated_s1 (0.11 h) are listed separately.",
    ]:
        w(f"- {d}")
    w("\n## 8. Incidents (details in the lab notebook, entries dated 2026-09-15 … 2026-09-19)\n")
    for i in [
        "2026-09-15: eval_grpo_mixed_s1 hung at vLLM engine init (fork + libgomp); fixed with spawn.",
        "2026-09-15: eval stage skipped step-200 val and never filled the val curve; fixed with per-step stash.",
        "2026-09-16: train_grpo_curated_s1 OOM in the step-5 backward (allocator fragmentation); fixed with expandable_segments; run restarted from step 1.",
        "2026-09-19: post-eval sync gaps of 12–17 idle minutes against the 30-minute guard; sync made incremental; queue restarted between jobs. The guard was never disabled.",
    ]:
        w(f"- {i}")
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {a.out} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
